[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ppl = "BwuFwsA11B4tnCeB8kAAeNnNM6NBL4WrDaHdn1koeYVY"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
