[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ppl = "BwuFwsA11B4tnCeB8kAAeNnNM6NBL4WrDaHdn1koeYVY"

[registry]
url = "https:127.0.0.1:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
