[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
# Home 7700 Change
# ppl = "ijo8fHCzsMSbEsGfz8anAenQ2BdToa9SmMx15pRmomo"
ppl = "AvcAWV2c4ieSgc3g2Bufx4cYnNS1ZiWh2pP3vsn8G9Ud"

[registry]
url = "https:127.0.0.1:8899"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
