[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
spl = "99Y76UAMBqcPn3kMPfFmfhQ2DP7mxYFeH1veVqP8nrps"

[registry]
url = "https:127.0.0.1:8899"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
